# -*- coding: utf-8 -*-
"""app_Starbucks

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1175AGglY0g_gsA9bdkHyGQZmdcz2nNMV
"""

import streamlit as st
import joblib
import numpy as np

# Load the saved model
model_path = "Starbucks_MLR.pkl"
model = joblib.load(model_path)

# Title
st.title("Starbucks MLR Prediction Model")

# Input fields
amount_prepaid = st.number_input("Amount of Prepaid Card", min_value=0.0, step=0.1)
age = st.number_input("Age", min_value=0, step=1)
days_per_month = st.number_input("Days per month at Starbucks", min_value=0, step=1)
income = st.number_input("Income", min_value=0.0, step=100.0)

# Predict button
if st.button("Predict"):
    input_data = np.array([[amount_prepaid, age, days_per_month, income]])
    prediction = model.predict(input_data)
    st.write("### Predicted Cups of Coffee per day:", round(prediction[0], 2))