# -*- coding: utf-8 -*-
"""app_Starbucks

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1175AGglY0g_gsA9bdkHyGQZmdcz2nNMV
"""

# -- coding: utf-8 --
"""app_starbucks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nQfDfQlql61s1U_WnheZklrt-bIyY2u2
"""

import streamlit as st
import joblib
import numpy as np

# Load the pre-trained model
model_path = 'Starbucks_MLR.pkl'
model = joblib.load(model_path)

# Streamlit app title
st.title('Starbucks MLR Prediction Model')

# Input fields
amount_prepaid = st.number_input('Amount of Prepaid card', min_value=0.0, format="%.2f")
age = st.number_input('Age', min_value=0, format="%d")
days_per_month = st.number_input('Days per month at Starbucks', min_value=0, format="%d")
income = st.number_input('Income', min_value=0.0, format="%.2f")

# Predict button
if st.button('Predict Cups of Coffee per day'):
    input_data = np.array([[amount_prepaid, age, days_per_month, income]])
    prediction = model.predict(input_data)
    st.write('Predicted Cups of Coffee per day:', round(prediction[0], 2))